/**
 * CoreX — Complete Supabase Database Schema
 *
 * This SQL is executed when admin clicks "Initialize Database" on the DB Init page.
 * It creates all required tables, indexes, and RLS policies.
 *
 * Design principles:
 * - Each Zustand store maps to one or more tables
 * - JSONB columns for complex nested data (features, device_pricing, etc.)
 * - RLS policies: service role has full access, anon key is restricted
 * - Real-time enabled on all tables
 * - Auto-generated IDs via UUID defaults
 */

export const COREX_SCHEMA_SQL = `
-- ══════════════════════════════════════════════════════════
-- CoreX Database Schema v1.0.0
-- Auto-generated by CoreX DB Init
-- ══════════════════════════════════════════════════════════

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ══════════════════════════════════════════════════════════
-- 1. USERS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  avatar TEXT DEFAULT '',
  provider TEXT NOT NULL DEFAULT 'google',
  balance DOUBLE PRECISION NOT NULL DEFAULT 0,
  referral_code TEXT NOT NULL,
  total_referrals INTEGER NOT NULL DEFAULT 0,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin', 'moderator')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'banned', 'suspended')),
  joined_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD')),
  subscriptions INTEGER NOT NULL DEFAULT 0,
  devices INTEGER NOT NULL DEFAULT 0,
  last_active TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 2. PLANS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS plans (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  speed TEXT NOT NULL DEFAULT '',
  bandwidth_type TEXT NOT NULL DEFAULT 'limited' CHECK (bandwidth_type IN ('unlimited', 'limited')),
  bandwidth_limit TEXT NOT NULL DEFAULT '50 GB',
  duration TEXT NOT NULL DEFAULT '30d',
  base_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  device_pricing JSONB NOT NULL DEFAULT '{}',
  max_devices INTEGER NOT NULL DEFAULT 5,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_featured BOOLEAN NOT NULL DEFAULT false,
  subscribers INTEGER NOT NULL DEFAULT 0,
  proxy_preset_id TEXT,
  features JSONB NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 3. SUBSCRIPTIONS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS subscriptions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL,
  plan TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'renewable')),
  start_date TEXT NOT NULL,
  expiry_date TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL DEFAULT 0,
  bandwidth_used DOUBLE PRECISION NOT NULL DEFAULT 0,
  bandwidth_limit DOUBLE PRECISION NOT NULL DEFAULT 0,
  deep_link TEXT NOT NULL DEFAULT '',
  devices INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 4. BALANCE REQUESTS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS balance_requests (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL DEFAULT '',
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  method TEXT NOT NULL DEFAULT 'bkash' CHECK (method IN ('bkash', 'nagad')),
  trx_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  submitted_at TEXT NOT NULL,
  admin_note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 5. TRANSACTIONS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS transactions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL DEFAULT 'payment' CHECK (type IN ('payment', 'topup', 'refund')),
  description TEXT NOT NULL DEFAULT '',
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('completed', 'pending', 'failed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 6. PAYMENT CONFIG TABLE (single-row settings)
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS payment_config (
  id TEXT PRIMARY KEY DEFAULT 'config_001',
  bkash_number TEXT NOT NULL DEFAULT '',
  bkash_type TEXT NOT NULL DEFAULT 'personal' CHECK (bkash_type IN ('personal', 'merchant')),
  nagad_number TEXT NOT NULL DEFAULT '',
  nagad_type TEXT NOT NULL DEFAULT 'personal' CHECK (nagad_type IN ('personal', 'merchant')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 7. TICKETS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS tickets (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'closed')),
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
  created_at TEXT NOT NULL,
  last_update TEXT NOT NULL,
  messages_count INTEGER NOT NULL DEFAULT 0,
  created_at_ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 8. TICKET MESSAGES TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS ticket_messages (
  id TEXT PRIMARY KEY,
  ticket_id TEXT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  sender TEXT NOT NULL DEFAULT 'user' CHECK (sender IN ('user', 'admin')),
  name TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  timestamp TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 9. COUPONS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS coupons (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL DEFAULT 'percentage' CHECK (type IN ('percentage', 'fixed')),
  value DOUBLE PRECISION NOT NULL DEFAULT 0,
  min_purchase DOUBLE PRECISION NOT NULL DEFAULT 0,
  max_discount DOUBLE PRECISION NOT NULL DEFAULT 0,
  max_claims INTEGER NOT NULL DEFAULT 0,
  current_claims INTEGER NOT NULL DEFAULT 0,
  applicable_plans JSONB NOT NULL DEFAULT '[]',
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  claimed_by JSONB NOT NULL DEFAULT '[]',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 10. REFERRALS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS referrals (
  id TEXT PRIMARY KEY,
  referrer_id TEXT NOT NULL,
  referrer_name TEXT NOT NULL DEFAULT '',
  referred_user_id TEXT NOT NULL,
  referred_user_name TEXT NOT NULL DEFAULT '',
  referral_code TEXT NOT NULL,
  referred_at TEXT NOT NULL,
  referrer_reward DOUBLE PRECISION NOT NULL DEFAULT 0,
  referred_reward DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('completed', 'pending')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 11. REFERRAL SETTINGS TABLE (single-row)
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS referral_settings (
  id TEXT PRIMARY KEY DEFAULT 'settings_001',
  referrer_reward DOUBLE PRECISION NOT NULL DEFAULT 5,
  referred_reward DOUBLE PRECISION NOT NULL DEFAULT 5,
  min_withdrawal DOUBLE PRECISION NOT NULL DEFAULT 10,
  commission_type TEXT NOT NULL DEFAULT 'fixed' CHECK (commission_type IN ('fixed', 'percentage')),
  commission_value DOUBLE PRECISION NOT NULL DEFAULT 5,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 12. UTILITY CONFIG TABLE (single-row)
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS utility_config (
  id TEXT PRIMARY KEY DEFAULT 'config_001',
  apk_download_url TEXT NOT NULL DEFAULT '',
  apk_version TEXT NOT NULL DEFAULT '',
  tutorial_url TEXT NOT NULL DEFAULT '',
  tutorial_title TEXT NOT NULL DEFAULT '',
  app_changelog TEXT NOT NULL DEFAULT '',
  telegram_link TEXT NOT NULL DEFAULT 'Coming Soon',
  facebook_link TEXT NOT NULL DEFAULT 'Coming Soon',
  registration_enabled BOOLEAN NOT NULL DEFAULT true,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 13. PROXY PRESETS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS proxy_presets (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT true,
  assigned_users INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 14. PROXY PRESET SUBGROUPS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS proxy_preset_subgroups (
  id TEXT PRIMARY KEY,
  preset_id TEXT NOT NULL REFERENCES proxy_presets(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  proxy_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'healthy' CHECK (status IN ('healthy', 'degraded', 'down')),
  image TEXT,
  image_width INTEGER DEFAULT 200,
  image_height INTEGER DEFAULT 100,
  proxy_ids JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 15. PROXIES TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS proxies (
  id TEXT PRIMARY KEY,
  protocol TEXT NOT NULL,
  address TEXT NOT NULL,
  port INTEGER NOT NULL,
  -- Auth fields (nullable)
  uuid TEXT,
  password TEXT,
  username TEXT,
  -- VLESS/VMess specific
  flow TEXT,
  network TEXT,
  tls BOOLEAN,
  sni TEXT,
  alpn TEXT,
  cipher TEXT,
  alter_id INTEGER,
  skip_cert_verify BOOLEAN,
  -- Reality
  reality_public_key TEXT,
  reality_short_id TEXT,
  client_fingerprint TEXT,
  -- gRPC
  grpc_service TEXT,
  -- WebSocket
  ws_path TEXT,
  ws_host TEXT,
  -- SS specific
  udp BOOLEAN,
  plugin TEXT,
  plugin_opts_mode TEXT,
  plugin_opts_host TEXT,
  -- SSR specific
  ssr_protocol TEXT,
  obfs TEXT,
  obfs_param TEXT,
  -- WireGuard
  private_key TEXT,
  public_key TEXT,
  preshared_key TEXT,
  dns TEXT,
  mtu INTEGER,
  -- Status
  status TEXT NOT NULL DEFAULT 'unknown' CHECK (status IN ('online', 'offline', 'unknown', 'degraded')),
  latency INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 16. ACTIVITY LOGS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS activity_logs (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL DEFAULT 'normal' CHECK (type IN ('normal', 'paid', 'referral')),
  user_name TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL DEFAULT '',
  timestamp TEXT NOT NULL,
  ip TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 17. ADMIN 2FA TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS admin_2fa (
  id TEXT PRIMARY KEY DEFAULT '2fa_001',
  is_enabled BOOLEAN NOT NULL DEFAULT false,
  secret TEXT,
  backup_codes JSONB NOT NULL DEFAULT '[]',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 18. BROADCASTS TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS broadcasts (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL DEFAULT 'info' CHECK (type IN ('info', 'warning', 'urgent')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TEXT NOT NULL,
  expires_at TEXT,
  created_at_ts TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- 19. CMS / RULES TABLE
-- ══════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS cms_content (
  id TEXT PRIMARY KEY DEFAULT 'cms_001',
  terms_of_service TEXT NOT NULL DEFAULT '',
  privacy_policy TEXT NOT NULL DEFAULT '',
  faq TEXT NOT NULL DEFAULT '[]',
  about_content TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════
-- INDEXES
-- ══════════════════════════════════════════════════════════
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_balance_requests_user_id ON balance_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_balance_requests_status ON balance_requests(status);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_tickets_user_id ON tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_id ON ticket_messages(ticket_id);
CREATE INDEX IF NOT EXISTS idx_referrals_referrer_id ON referrals(referrer_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_timestamp ON activity_logs(timestamp);

-- ══════════════════════════════════════════════════════════
-- REALTIME — Enable for all tables
-- ══════════════════════════════════════════════════════════
ALTER PUBLICATION supabase_realtime ADD TABLE users;
ALTER PUBLICATION supabase_realtime ADD TABLE plans;
ALTER PUBLICATION supabase_realtime ADD TABLE subscriptions;
ALTER PUBLICATION supabase_realtime ADD TABLE balance_requests;
ALTER PUBLICATION supabase_realtime ADD TABLE transactions;
ALTER PUBLICATION supabase_realtime ADD TABLE payment_config;
ALTER PUBLICATION supabase_realtime ADD TABLE tickets;
ALTER PUBLICATION supabase_realtime ADD TABLE ticket_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE coupons;
ALTER PUBLICATION supabase_realtime ADD TABLE referrals;
ALTER PUBLICATION supabase_realtime ADD TABLE referral_settings;
ALTER PUBLICATION supabase_realtime ADD TABLE utility_config;
ALTER PUBLICATION supabase_realtime ADD TABLE proxy_presets;
ALTER PUBLICATION supabase_realtime ADD TABLE proxy_preset_subgroups;
ALTER PUBLICATION supabase_realtime ADD TABLE proxies;
ALTER PUBLICATION supabase_realtime ADD TABLE activity_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE admin_2fa;
ALTER PUBLICATION supabase_realtime ADD TABLE broadcasts;
ALTER PUBLICATION supabase_realtime ADD TABLE cms_content;

-- ══════════════════════════════════════════════════════════
-- RLS POLICIES — Service role bypasses RLS, anon is restricted
-- ══════════════════════════════════════════════════════════

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE balance_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE utility_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE proxy_presets ENABLE ROW LEVEL SECURITY;
ALTER TABLE proxy_preset_subgroups ENABLE ROW LEVEL SECURITY;
ALTER TABLE proxies ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_2fa ENABLE ROW LEVEL SECURITY;
ALTER TABLE broadcasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_content ENABLE ROW LEVEL SECURITY;

-- Anon key: allow SELECT on most tables (for client-side reads)
-- All writes go through API routes using the service role key
CREATE POLICY "Allow anon select on users" ON users FOR SELECT USING (true);
CREATE POLICY "Allow anon select on plans" ON plans FOR SELECT USING (true);
CREATE POLICY "Allow anon select on subscriptions" ON subscriptions FOR SELECT USING (true);
CREATE POLICY "Allow anon select on balance_requests" ON balance_requests FOR SELECT USING (true);
CREATE POLICY "Allow anon select on transactions" ON transactions FOR SELECT USING (true);
CREATE POLICY "Allow anon select on payment_config" ON payment_config FOR SELECT USING (true);
CREATE POLICY "Allow anon select on tickets" ON tickets FOR SELECT USING (true);
CREATE POLICY "Allow anon select on ticket_messages" ON ticket_messages FOR SELECT USING (true);
CREATE POLICY "Allow anon select on coupons" ON coupons FOR SELECT USING (true);
CREATE POLICY "Allow anon select on referrals" ON referrals FOR SELECT USING (true);
CREATE POLICY "Allow anon select on referral_settings" ON referral_settings FOR SELECT USING (true);
CREATE POLICY "Allow anon select on utility_config" ON utility_config FOR SELECT USING (true);
CREATE POLICY "Allow anon select on proxy_presets" ON proxy_presets FOR SELECT USING (true);
CREATE POLICY "Allow anon select on proxy_preset_subgroups" ON proxy_preset_subgroups FOR SELECT USING (true);
CREATE POLICY "Allow anon select on proxies" ON proxies FOR SELECT USING (true);
CREATE POLICY "Allow anon select on broadcasts" ON broadcasts FOR SELECT USING (true);
CREATE POLICY "Allow anon select on cms_content" ON cms_content FOR SELECT USING (true);

-- ══════════════════════════════════════════════════════════
-- SEED DEFAULT CONFIG ROWS
-- ══════════════════════════════════════════════════════════
INSERT INTO payment_config (id, bkash_number, bkash_type, nagad_number, nagad_type)
VALUES ('config_001', '01712345678', 'personal', '01812345678', 'personal')
ON CONFLICT (id) DO NOTHING;

INSERT INTO referral_settings (id, referrer_reward, referred_reward, min_withdrawal, commission_type, commission_value)
VALUES ('settings_001', 5, 5, 10, 'fixed', 5)
ON CONFLICT (id) DO NOTHING;

INSERT INTO utility_config (id, apk_download_url, apk_version, tutorial_url, tutorial_title, app_changelog, telegram_link, facebook_link, registration_enabled)
VALUES ('config_001', 'https://corex.io/download/corex-v2.5.3.apk', 'v2.5.3', 'https://corex.io/tutorial/getting-started', 'Getting Started with CoreX', '• Fixed connection stability\n• Added WireGuard protocol\n• Improved load balancing\n• Dark mode improvements', 'Coming Soon', 'Coming Soon', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO admin_2fa (id, is_enabled, secret, backup_codes)
VALUES ('2fa_001', false, NULL, '[]')
ON CONFLICT (id) DO NOTHING;

INSERT INTO cms_content (id, terms_of_service, privacy_policy, faq, about_content)
VALUES ('cms_001', '', '', '[]', '')
ON CONFLICT (id) DO NOTHING;
`

/**
 * List of all CoreX tables for status checking
 */
export const COREX_TABLES = [
  'users',
  'plans',
  'subscriptions',
  'balance_requests',
  'transactions',
  'payment_config',
  'tickets',
  'ticket_messages',
  'coupons',
  'referrals',
  'referral_settings',
  'utility_config',
  'proxy_presets',
  'proxy_preset_subgroups',
  'proxies',
  'activity_logs',
  'admin_2fa',
  'broadcasts',
  'cms_content',
]

/**
 * SQL to DROP all tables (for reset)
 */
export const COREX_DROP_SQL = `
DROP TABLE IF EXISTS cms_content CASCADE;
DROP TABLE IF EXISTS broadcasts CASCADE;
DROP TABLE IF EXISTS admin_2fa CASCADE;
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS proxies CASCADE;
DROP TABLE IF EXISTS proxy_preset_subgroups CASCADE;
DROP TABLE IF EXISTS proxy_presets CASCADE;
DROP TABLE IF EXISTS utility_config CASCADE;
DROP TABLE IF EXISTS referral_settings CASCADE;
DROP TABLE IF EXISTS referrals CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS ticket_messages CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS payment_config CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS balance_requests CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS plans CASCADE;
DROP TABLE IF EXISTS users CASCADE;
`
